function [] = test3()
n = 10;
maxIt = 1000;
tol = 1e-10;
miu = 0;

start = "Test 3\n" + ...
    "Test ten sprawdza poprawność metody dla\n" + ...
    "macierzy o różnych rozmiarach.\n" + ...
    "Utworzona zostanie macierz A następnie będziemy\n" + ...
    "brać jej coraz większe wycinki idąc od elemntu A(1:1)\n" + ...
    "Maksymalna liczba iteracji = %d\n" + ...
    "Maksymalny dopuszczalny błąd = %d\n" + ...
    "Miu = %d %+di\n" + ...
    "Jeżeli liczba iteracji jest większa niż maxIt wynik może\n" + ...
    "być błędny\n";

fprintf(start, maxIt, tol, real(miu), imag(miu));
pause;

trueRes = 1;
A = eye(n);
A(2:end,2:end) = A(2:end,2:end).*(randi(100,n-1) - 50);
display(A);
fprintf("==========================================================" + ...
    "==================\n");
fprintf("│wyznaczona wartość%*s│błąd wyniku%*s│błąd przybliżeń%*s" + ...
    "│liczba iteracji%*s│n │\n", 4,"", 2,"", 0,"", 0, "");
fprintf("===========================================================" + ...
    "=================\n");
pause;
for i = 1:n
    [res, it, err] = P2Z42_AZY_eigenvalue(A(1:i,1:i),miu,tol,maxIt);
    t =  sprintf("%d",abs(res - trueRes));

    fprintf("│%-+10f%-+10fi │%-13s│%-15d│%-15d│%-2d│\n", ...
        real(res), imag(res), t, err, it, i);
    fprintf("=============================================" + ...
        "===============================\n");

end
end% function

